# Generated by Django 2.2.2 on 2019-06-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-me/')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('curriculum_vitae', models.FileField(upload_to='about-me/')),
            ],
            options={
                'verbose_name_plural': 'Acerca de mi',
                'verbose_name': 'Acerca de mi',
            },
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_review/')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('job_title', models.CharField(max_length=80, verbose_name='Cargo')),
                ('review', models.TextField(max_length=200, verbose_name='Comentario')),
            ],
            options={
                'verbose_name_plural': 'Comentarios de clientes',
                'verbose_name': 'Comentario de cliente',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('subject', models.CharField(max_length=70, verbose_name='Asunto')),
                ('message', models.TextField(max_length=600, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name_plural': 'Mensajes de contacto',
                'verbose_name': 'Mensaje de contacto',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('E', 'Educación'), ('T', 'Corporación')], max_length=10, verbose_name='Tipo de institución')),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'verbose_name': 'Institución',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('score', models.FloatField(verbose_name='Puntaje')),
            ],
            options={
                'verbose_name_plural': 'Habilidades profesionales',
                'verbose_name': 'Habilidad profesional',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
            ],
            options={
                'verbose_name_plural': 'Categorías de proyectos',
                'verbose_name': 'Categoría de proyecto',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20, verbose_name='Icono')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Lo que hago',
                'verbose_name': 'Lo que hago',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site-config/')),
                ('title', models.CharField(max_length=20, verbose_name='Título del sítio')),
                ('person', models.CharField(max_length=50, verbose_name='Nombre de la persona')),
                ('job_title', models.CharField(max_length=50, verbose_name='Título o cargo de la persona')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico de la persona')),
                ('cellphone', models.CharField(max_length=50, verbose_name='Teléfono ó Celular de la persona')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección o lugar de ubicación de la persona')),
                ('copyright', models.CharField(max_length=100, verbose_name='Derechos de autor')),
            ],
            options={
                'verbose_name_plural': 'Configuración del sitio',
                'verbose_name': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20, verbose_name='Icono de la red social')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre de la red social')),
                ('url', models.URLField(max_length=60, verbose_name='URL de la red social')),
            ],
            options={
                'verbose_name_plural': 'Redes sociales',
                'verbose_name': 'Red social',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('score', models.FloatField(verbose_name='Puntaje')),
            ],
            options={
                'verbose_name_plural': 'Habilidades técnicas',
                'verbose_name': 'Habilidad técnica',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.Institution', verbose_name='Institución educativa')),
            ],
            options={
                'verbose_name_plural': 'Experiencias laborales',
                'verbose_name': 'Experiencia laboral',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.ProjectCategory', verbose_name='Categoría de proyecto')),
                ('technical_skills', models.ManyToManyField(to='landing.TechnicalSkill', verbose_name='Tecnologías o herramientas')),
            ],
            options={
                'verbose_name_plural': 'Experiencias laborales',
                'verbose_name': 'Experiencia laboral',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneurial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-me/')),
                ('title', models.CharField(max_length=20, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=20, verbose_name='Subtítulo')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('url', models.URLField(max_length=60, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.ProjectCategory', verbose_name='Categoría de proyecto')),
            ],
            options={
                'verbose_name_plural': 'Emprendimientos',
                'verbose_name': 'Emprendimiento',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='landing.Institution', verbose_name='Institución educativa')),
            ],
            options={
                'verbose_name_plural': 'Educación',
                'verbose_name': 'Educación',
            },
        ),
    ]
