# Generated by Django 2.2.2 on 2019-06-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='curriculum_vitae',
            field=models.FileField(upload_to='about-me/', verbose_name='Hoja de vida'),
        ),
    ]
