# Generated by Django 2.2.2 on 2019-06-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190628_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(upload_to='about-me/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='image',
            field=models.ImageField(upload_to='client_review/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='entrepreneurial',
            name='image',
            field=models.ImageField(upload_to='about-me/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Imágen'),
        ),
    ]
