# Generated by Django 2.2.2 on 2019-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190628_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskill',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Dirección o lugar de ubicación de la persona'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='cellphone',
            field=models.CharField(max_length=12, verbose_name='Teléfono ó Celular de la persona'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright',
            field=models.CharField(max_length=150, verbose_name='Derechos de autor'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Correo electrónico de la persona'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='image',
            field=models.ImageField(upload_to='site-config/', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='job_title',
            field=models.CharField(max_length=60, verbose_name='Título o cargo de la persona'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='person',
            field=models.CharField(max_length=60, verbose_name='Nombre de la persona'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Título del sítio'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Puntaje'),
        ),
    ]
