# Generated by Django 2.2.2 on 2019-06-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20190629_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['name'], 'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
