# Generated by Django 2.2.2 on 2019-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190629_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Orden'),
        ),
    ]
