# Generated by Django 2.2.2 on 2019-06-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20190629_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['order'], 'verbose_name': 'Red social', 'verbose_name_plural': 'Redes sociales'},
        ),
    ]
