# Generated by Django 2.2.2 on 2019-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20190629_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=30, verbose_name='Icono'),
        ),
    ]
