# Generated by Django 2.2.2 on 2019-06-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20190629_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskill',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje (%)'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje (%)'),
        ),
    ]
