# Generated by Django 2.2.2 on 2019-07-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_portfolio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientreview',
            old_name='image',
            new_name='client_image',
        ),
        migrations.RemoveField(
            model_name='clientreview',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='clientreview',
            name='name',
        ),
        migrations.AddField(
            model_name='clientreview',
            name='client_job_title',
            field=models.CharField(default=1, max_length=80, verbose_name='Cargo del cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientreview',
            name='client_name',
            field=models.CharField(default=1, max_length=60, verbose_name='Nombre del cliente'),
            preserve_default=False,
        ),
    ]
